// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_events.sql

package repository

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_events (event_id,
                          event_type,
                          event_version,
                          source_service,
                          actor_type,
                          actor_id,
                          aggregate_type,
                          aggregate_id,
                          tenant_id,
                          status,
                          ip_address,
                          user_agent,
                          trace_id,
                          details)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14) RETURNING id, event_id, event_type, event_version, source_service, actor_type, actor_id, aggregate_type, aggregate_id, tenant_id, status, created_at, ip_address, user_agent, trace_id, details
`

type CreateAuditEventParams struct {
	EventID       uuid.UUID   `json:"event_id"`
	EventType     string      `json:"event_type"`
	EventVersion  int32       `json:"event_version"`
	SourceService string      `json:"source_service"`
	ActorType     pgtype.Text `json:"actor_type"`
	ActorID       *uuid.UUID  `json:"actor_id"`
	AggregateType string      `json:"aggregate_type"`
	AggregateID   uuid.UUID   `json:"aggregate_id"`
	TenantID      *uuid.UUID  `json:"tenant_id"`
	Status        pgtype.Text `json:"status"`
	IpAddress     *netip.Addr `json:"ip_address"`
	UserAgent     pgtype.Text `json:"user_agent"`
	TraceID       pgtype.Text `json:"trace_id"`
	Details       []byte      `json:"details"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, createAuditEvent,
		arg.EventID,
		arg.EventType,
		arg.EventVersion,
		arg.SourceService,
		arg.ActorType,
		arg.ActorID,
		arg.AggregateType,
		arg.AggregateID,
		arg.TenantID,
		arg.Status,
		arg.IpAddress,
		arg.UserAgent,
		arg.TraceID,
		arg.Details,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventType,
		&i.EventVersion,
		&i.SourceService,
		&i.ActorType,
		&i.ActorID,
		&i.AggregateType,
		&i.AggregateID,
		&i.TenantID,
		&i.Status,
		&i.CreatedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.TraceID,
		&i.Details,
	)
	return i, err
}
