// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID            uuid.UUID   `json:"id"`
	EventID       uuid.UUID   `json:"event_id"`
	EventType     string      `json:"event_type"`
	EventVersion  int32       `json:"event_version"`
	SourceService string      `json:"source_service"`
	ActorType     pgtype.Text `json:"actor_type"`
	ActorID       *uuid.UUID  `json:"actor_id"`
	AggregateType string      `json:"aggregate_type"`
	AggregateID   uuid.UUID   `json:"aggregate_id"`
	TenantID      *uuid.UUID  `json:"tenant_id"`
	Status        pgtype.Text `json:"status"`
	CreatedAt     time.Time   `json:"created_at"`
	IpAddress     *netip.Addr `json:"ip_address"`
	UserAgent     pgtype.Text `json:"user_agent"`
	TraceID       pgtype.Text `json:"trace_id"`
	Details       []byte      `json:"details"`
}

type ProcessedEvent struct {
	EventID      uuid.UUID `json:"event_id"`
	EventType    string    `json:"event_type"`
	EventVersion int32     `json:"event_version"`
	ProcessedAt  time.Time `json:"processed_at"`
}
