// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: processed_events.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createProcessedEvent = `-- name: CreateProcessedEvent :one
INSERT INTO processed_events (
    event_id,
    event_type,
    event_version
)
VALUES (
           $1,
           $2,
           $3
       )
    ON CONFLICT (event_id) DO NOTHING
RETURNING event_id, event_type, event_version, processed_at
`

type CreateProcessedEventParams struct {
	EventID      uuid.UUID `json:"event_id"`
	EventType    string    `json:"event_type"`
	EventVersion int32     `json:"event_version"`
}

func (q *Queries) CreateProcessedEvent(ctx context.Context, arg CreateProcessedEventParams) (ProcessedEvent, error) {
	row := q.db.QueryRow(ctx, createProcessedEvent, arg.EventID, arg.EventType, arg.EventVersion)
	var i ProcessedEvent
	err := row.Scan(
		&i.EventID,
		&i.EventType,
		&i.EventVersion,
		&i.ProcessedAt,
	)
	return i, err
}

const isEventProcessed = `-- name: IsEventProcessed :one
SELECT EXISTS (
    SELECT 1
    FROM processed_events
    WHERE event_id = $1
) AS processed
`

func (q *Queries) IsEventProcessed(ctx context.Context, eventID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isEventProcessed, eventID)
	var processed bool
	err := row.Scan(&processed)
	return processed, err
}
