// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error)
	CreateProcessedEvent(ctx context.Context, arg CreateProcessedEventParams) (ProcessedEvent, error)
	IsEventProcessed(ctx context.Context, eventID uuid.UUID) (bool, error)
}

var _ Querier = (*Queries)(nil)
