-- name: CreateAuditEvent :one
INSERT INTO audit_events (event_id,
                          event_type,
                          event_version,
                          source_service,
                          actor_type,
                          actor_id,
                          aggregate_type,
                          aggregate_id,
                          tenant_id,
                          status,
                          ip_address,
                          user_agent,
                          trace_id,
                          details)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14) RETURNING *;